/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/courses` | `/courses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `/course/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/lesson/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/paper/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/paper/result/[attemptId]`, params: Router.UnknownInputParams & { attemptId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/courses` | `/courses`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/course/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/lesson/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/paper/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/paper/result/[attemptId]`, params: Router.UnknownOutputParams & { attemptId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/courses${`?${string}` | `#${string}` | ''}` | `/courses${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/profile/edit${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/courses` | `/courses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/edit`; params?: Router.UnknownInputParams; } | `/course/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/lesson/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/paper/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/paper/result/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/course/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/lesson/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/paper/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/paper/result/[attemptId]`, params: Router.UnknownInputParams & { attemptId: string | number; } };
    }
  }
}
