export const paths = {
  login: '/login',
  admin: {
    root: '/admin',
    dashboard: '/admin',
    students: '/admin/students',
    studentDetail: (id: number | string) => `/admin/students/${id}`,
    industries: '/admin/industries',
    professions: '/admin/professions',
    courses: '/admin/courses',
    courseNew: '/admin/courses/new',
    courseEdit: (id: number | string) => `/admin/courses/${id}/edit`,
    coursePaper: (id: number | string) => `/admin/courses/${id}/paper`,
    courseCategories: '/admin/courses/categories',
    services: '/admin/services',
    serviceNew: '/admin/services/new',
    serviceEdit: (id: number | string) => `/admin/services/${id}/edit`,
    servicePurchases: '/admin/service-purchases',
    orders: '/admin/orders',
    checklists: '/admin/checklists',
    homeBanners: '/admin/mobile/home-banners',
    homeBannerNew: '/admin/mobile/home-banners/new',
    homeBannerEdit: (id: number | string) => `/admin/mobile/home-banners/${id}/edit`,
    settingsBankDetails: '/admin/settings/bank-details',
    settingsAppIntro: '/admin/settings/app-intro',
  },
} as const;
